name: Publish Beta Image

on:
  push:
    branches: ["main"]

jobs:
  publish-beta-image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Main
        uses: actions/checkout@main

      - name: Publish Image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: nfcopier/{{<PROJECT_NAME>}}
          username: ${{secrets.HARBOR_GITHUB_USERNAME}}
          password: ${{secrets.HARBOR_GITHUB_PASSWORD}}
          tags: beta-${{github.run_number}}
