name: Publish Beta Image

on:
  pull_request:
    types: "closed"

jobs:
  publish-beta-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Main
        uses: actions/checkout@main

      - name: Publish Image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: {{<PROJECT_OWNER>}}/{{<PROJECT_NAME>}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: beta-${{github.run_number}}
