name: Publish Production Image

on:
  release:
    types:
      - published

jobs:
  push-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: nfcopier/{{<PROJECT_NAME>}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          tag_names: true
          tag_semver: true
