name: Publish Production Image

on:
  release:
    types:
      - published

jobs:
  push-release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Main
        uses: actions/checkout@main

      - name: Publish Image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: nfcopier/{{<PROJECT_NAME>}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          tag_names: true
          tag_semver: true
