name: Publish Beta Image

on:
  push:
    branches: ["main"]

jobs:
  push-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: nfcopier/{{<PROJECT_NAME>}}
          username: ${{secrets.HARBOR_GITHUB_USERNAME}}
          password: ${{secrets.HARBOR_GITHUB_PASSWORD}}
          tags: beta-${{github.run_number}}
