name: Replace Template Variables

on:
  push:
    branches: "main"
    tags: "infrastructure-update"

jobs:
  replace-template-variables:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Replace Variables
        run: |
          echo 'Removing Workflow file'
          rm -f '.github/workflows/replace-template-variables.yml'
          echo 'Replacing {{<PROJECT_NAME>}}'
          repoName=$(echo $REPO_NAME | sed 's/\//\\\//g')
          grep -rl '{{<PROJECT_NAME>}}' | xargs sed -i "s/{{<PROJECT_NAME>}}/${repoName}/g"
          echo 'Replacing {{<COPYRIGHT_OWNER>}}'
          grep -rl '{{<COPYRIGHT_OWNER>}}' | xargs sed -i "s/{{<COPYRIGHT_OWNER}}/${OWNER_NAME}/g"
        env:
          REPO_NAME: ${{github.repository}}
          OWNER_NAME: ${{github.repository_owner}}

      - name: Commit & Push changes
        run: |
          git config --global user.name 'Infrastructure Bot'
          git config --global user.email 'InfrastructureBot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${TF_TOKEN}@github.com/${REPO_NAME}
          git commit -am 'Infrastructure update'
          git push
        env:
          REPO_NAME: ${{github.repository}}
          TF_TOKEN: ${{secrets.TERRAFORM_TOKEN}}
