name: Replace Template Variables

on:
  push:
    branches: "main"
    tags: "infrastructure-change"

jobs:
  replace-template-variables:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Replace Variables
        uses: actions/github-script@v6
        with:
          script: console.log("Hello world!");
